---
Name: ecommerce_security
Before: 'mysite/*'
After: 'framework/*','cms/*','ecommerce/*'
---

Member:
  extensions:
    - EcommerceSecurityMemberDecoration

SecurityCheck_ModelAdmin:
  managed_models:
    - EcommerceSecurityBaseClass

---
After: 'framework/*','cms/*','ecommerce/*','mysite/*'
Only:
  moduleexists: 'grouped-cms-menu'
---
LeftAndMain:
  menu_groups:
    Shop:
      priority: -500
      - SecurityCheck_ModelAdmin
