---
Name: ecommerce_security
Before: 'mysite/*'
After: 'framework/*','cms/*','ecommerce/*'
---
SecurityCheck_ModelAdmin:
  managed_models:
    - EcommerceSecurityBaseClass

---
Only:
  moduleexists: 'grouped-cms-menu'
---
LeftAndMain:
  menu_groups:
    Shop:
      - SecurityCheck_ModelAdmin
